### ISSUE TITLE
Support manual trim on ground

### ISSUE THREAD

**Issue by aguther** [aguther/airbus-fly-by-wire-matlab#1]
# Problem

The trim wheel cannot be moved because the fly-by-wire system is constantly writing it's value to the sim. For take-off it's usual that the pilots calculate the optimum trim setting and set it with the help of the trim wheel.

# Proposed solution

Write the elevator trim position only when automatic trim is active. Create a signal that tells if the elevator trim position should be written or not. This can be used by the integration code to determine if the value should be written. Additionally, read the value of the THS (`ELEVATOR TRIM POSITION`) from the sim. This value needs to be used to initialize the system on transition from ground to flight mode (to avoid a jump).

* on take-off it needs to be ensured that automatic trim starts from the take-off setting, otherwise there will be a jump
* on landing it needs to be ensured that reset of THS to 0° is awaited before controls "are released"
* one idea could be to compute a signal (0 or 1) that states if manual trim is allowed

# Tasks

- [x] read elevator trim from sim (variable `ELEVATOR TRIM POSITION, DEGREE`)
- [x] convert variable sign and unit according common theory
- [x] initialize automatic trim system with current trim value when blending to flight mode
- [x] create and calculate variable that outputs if the trim should be written
- [x] create variable that signals if the integrator should work or take an external signal directly
