### ISSUE TITLE
Use acceleration variable instead of calculated derivative for pitch attitude protections

### ISSUE THREAD

**Issue by aguther** [aguther/airbus-fly-by-wire-matlab#16]
# Problem

Currently the pitch attitude protections use for acceleration the calculated derivative from pitch rotation velocity. This has the downside that the calculated derivative creates a lot of noise in the signal.

# Proposed solution

Use the variable `BODY ROTATION ACCELERATION` directly from the sim.

# Tasks
- [x] read variable from sim
- [x] convert variable to common theory sign and unit
- [x] use value for pitch attitude protection

**Comment by RukusDM58** [comment]
Good call.  Derivative is inherently noisy
