### ISSUE TITLE
Switch deflection rate of auto trim depending on configuration

### ISSUE THREAD

**Issue by aguther** [aguther/airbus-fly-by-wire-matlab#2]
# Problem

Currently the automatic trim system always limits the deflection rate of the THS to 0.3 °/s. In the real plane this depends on the configuration. 

# Proposed solution

Introduce a state machine that determines the correct deflection rate based on configuration. The variable to be used in this first step is `FLAPS HANDLE INDEX`.

| Configuration | Flaps handle index | Limit |
|----------|-------------|------|
| Clean |  0 | 0.3 °/s |
| Flaps |  > 0 | 0.7 °/s |

# Tasks
- [x] Add variable `FLAPS HANDLE INDEX` as model input (bus)
- [x] Add state machine that determines the deflection rate based on flaps handle index
- [x] Use deflection rate in automatic trim system
