### ISSUE TITLE
Auto trim needs to freeze in certain conditions

### ISSUE THREAD

**Issue by aguther** [aguther/airbus-fly-by-wire-matlab#3]
# Problem

The automatic trim system freezes in certain conditions. Currently only the condition for nz is implemented.

# Proposed solution

Implement a state machine that provides a variable that signals automatic trim system to freeze. This state machine can be easily extended to support new conditions that might arise.

Up to now the following conditions are known and will be implemented:
- nz > 1.25
- nz < 0.5
- Radio Height < 50 ft
- Bank angle > 30 °

# Tasks
- [x] Add variable to bus that signals freezing of the trim
- [x] Add state machine that checks for the conditions and provides the signal
- [x] Use signal in automatic trim system
