### ISSUE TITLE
Use gear strut compression to detect ground instead of radio height

### ISSUE THREAD

**Issue by aguther** [aguther/airbus-fly-by-wire-matlab#4]
# Problem

Currently the detection of ground is based on the radio height.

# Proposed solution

Use variable `GEAR ANIMATION POSITION:index` for detection of ground. This value ranges from `0:0.5` to reflect the status of gear retracted to deployed. For values from `0.5:1.0` it reflects strut relaxed to fully compressed.

Proposal is to compute a new datum that ranges from `0.0:1.0` to represent the gear compression. This value should then be used for ground detection.

Open point: this solution does not take into account that the real plane also uses wheel speed for detection.

# Tasks

- [x] read variable `GEAR ANIMATION POSITION:index` for index 0, 1, 2
- [x] compute new variable for gear compression that transforms the input of `0.5:1.0` to `0.0:1.0`
- [x] use new variable in ground detection logic
