### ISSUE TITLE
Add flare mode

### ISSUE THREAD

**Issue by aguther** [aguther/airbus-fly-by-wire-matlab#5]
# Problem

The current implementation does not have a flare law. This forces the pilot to actively press the plane on the ground, which is not a natural behavior (in flare a pilot needs to typically pull the yoke/stick due to ground effect).

# Proposed solution

Add a flare flight control law to the system. Details have to be provided

## Open questions

- how does the transition from flare to flight mode look like?
  - Is is triggered by TOGA thrust setting?
  - Is it triggered by Theta > 8°?

# Tasks
- [x] add logic to signal flare mode to pitch law (`in_flare`)
- [x] add datum that filters Theta over 20 seconds (`flare_Theta_deg`)
- [x] add datum `flare_Theta_c_deg`
- [x] add datum `flare_Theta_c_rate_deg_s` that reflects the target rate (`flare_Theta_c_deg` -> -2° over 8 seconds)
- [x] add logic to set `flare_Theta_c_deg` to `flare_Theta_deg` at 50 ft (`H_radio_ft`)
- [x] add logic to set `flare_Theta_c_deg` to -2° at 30 ft (`H_radio_ft`)
- [x] add Theta feedback loop to pitch normal law that is enabled when signal `in_flare` is active and uses `flare_Theta_c_deg` as setpoint

# References

- Rudolf Brockhaus "Flugregelung"
